from playwright.sync_api import expect
import time

class LoginPage:
    def __init__(self, page):
        self.page = page

    def navigate(self):
        self.page.goto(self.url, wait_until="load")
        expect(self.page.get_by_text("One app for Human Resources")).to_be_visible()
    
    def loginUser(self):
        #expect(self.page.get_by_role("text", name="Login to Your Account")).to_be_visible()

        expect(self.page.get_by_label("Email address *")).to_be_visible()
        self.page.get_by_label("Email address *").click()
        self.page.get_by_label("Email address *").fill(self.email)
        
    def loginPass(self):
        expect(self.page.get_by_label("Password *")).to_be_visible()
        self.page.get_by_label("Password *").click()
        self.page.get_by_label("Password *").fill(self.password)

    def clickLogIn(self):
        expect(self.page.get_by_role("button", name="Log In")).to_be_visible()
        self.page.get_by_role("button", name="Log In").click()

class Dashboard(LoginPage):
    def __init__(self, page):
        self.page = page
        self.url = "https://test-pub-hris.robi.com.bd/"
        self.email = "riyad.salehdin@robi.com.bd"
        self.password = "Robi@12345$$"
        self.name = "Riyad Salehdin"
    
    def checkLoggedIn(self):
        expect(self.page.locator("app-breadcrumb").get_by_text("Dashboard")).to_be_visible()
        expect(self.page.locator("user").get_by_text(self.name)).to_be_visible()
        

    def logout(self):
        # self.page.pause()
        self.page.locator("user").get_by_text(self.name).click()
        self.page.get_by_role("button", name="Log out").click()
        expect(self.page.get_by_text("You have signed out!")).to_be_visible()
        #time.sleep(2)

    def loginShortcut(self):
        self.page.get_by_role("link", name="sign in").click()


#     page.locator("app-breadcrumb").get_by_text("Dashboard").click()
#     page.locator("user").get_by_text("Riyad Salehdin").click()
#     page.locator(".cdk-overlay-backdrop").click()
#     page.locator("user").get_by_text("Riyad Salehdin").click()
#     page.locator("#mat-dialog-1").click()
#     page.locator(".cdk-overlay-backdrop").click()
#     page.locator("fuse-fullscreen").get_by_role("button").click()
#     page.locator("fuse-fullscreen").get_by_role("button").click()
#     page.locator("fuse-fullscreen").get_by_role("button").click()
#     page.get_by_text("Tuesday, 7 January,").click()
#     expect(page.get_by_role("button", name="PMS Manual play")).to_be_visible()
#     page.locator("#automat_dashboard div").filter(has_text="0 Pending Leave").nth(3).click()
#     page.locator("#automat_dashboard div").filter(has_text="0 Pending Medical Claim").nth(3).click()
#     page.locator("#automat_dashboard div").filter(has_text="-- PMS Rating(2024)").nth(3).click()
#     page.locator("#automat_dashboard").get_by_text("Attendance").click()
#     page.locator("span").filter(has_text="Today").click()
#     page.get_by_text("Jan 7,").click()
#     page.get_by_text("In Time").click()
#     page.get_by_text("Out Time").click()
#     page.get_by_text("Today").first.click()
#     page.get_by_role("menuitem", name="Last 7 Days").click()
#     page.get_by_text("Last 7 Days").click()
#     page.get_by_role("menuitem", name="Today").click()
#     page.get_by_text("Today").first.click()
#     page.get_by_role("menuitem", name="Last 7 Days").click()
#     page.get_by_role("columnheader", name="Date").click()
#     page.get_by_role("columnheader", name="In Time").click()
#     page.get_by_role("columnheader", name="Out Time").click()
#     page.get_by_role("columnheader", name="Status").click()
#     page.get_by_text("All Benefits").click()
#     page.get_by_text("Benefit Title").click()
#     page.get_by_text("(Approved amount/Total limit)").click()
#     page.get_by_text("Useful Links").click()
#     expect(page.get_by_role("button", name="FSD")).to_be_visible()
#     with page.expect_popup() as page1_info:
#         page.get_by_role("button", name="Workflow").click()
#     page1 = page1_info.value
#     expect(page.get_by_role("button", name="Workflow")).to_be_visible()
#     expect(page.get_by_role("button", name="ServiceDesk Plus")).to_be_visible()
#     expect(page.get_by_role("button", name="Robi eApproval")).to_be_visible()
#     expect(page.get_by_role("button", name="Download iOS App")).to_be_visible()
#     expect(page.get_by_role("button", name="Download Android App")).to_be_visible()
#     expect(page.locator("#automat_dashboard").get_by_text("My Salary")).to_be_visible()
#     expect(page.get_by_text("My Salary 2025Select")).to_be_visible()
#     page.locator("span").filter(has_text="Select Year").click()
#     page.locator(".cdk-overlay-backdrop").click()
#     expect(page.locator("span").filter(has_text="Select Year")).to_be_visible()
#     expect(page.locator("span").filter(has_text="Select Month")).to_be_visible()
#     expect(page.get_by_text("Organogram")).to_be_visible()
#     expect(page.get_by_text("Announcements")).to_be_visible()
#     page.get_by_text("Today").click()
#     page.get_by_role("menuitem", name="Last 7 Days").click()
#     expect(page.get_by_text("last 7 Days", exact=True)).to_be_visible()
#     page.get_by_text("Announcements").click()
#     expect(page.get_by_text("Announcements last 7 Days")).to_be_visible()
#     expect(page.get_by_text("Organogram")).to_be_visible()

# import re
# from playwright.sync_api import Playwright, sync_playwright, expect


# def run(playwright: Playwright) -> None:
#     browser = playwright.chromium.launch(headless=False)
#     context = browser.new_context()
#     page = context.new_page()
#     page.goto("https://test-pub-hris.robi.com.bd/")
#     page.goto("https://test-pub-hris.robi.com.bd/sign-in?redirectURL=%2Fess%2Fdashboard")
#     page.get_by_label("Email address *").click()
#     page.get_by_label("Email address *").click()
#     page.get_by_label("Email address *").fill("riyad.salehdin@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.locator("mat-form-field").filter(has_text="Password *").click()
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("Robi@12345$$")
#     page.get_by_role("button", name="Log In").click()
#     page.locator("user div").first.click()
#     page.get_by_role("button", name="Log out").click()
#     page.get_by_text("You have signed out!").click()
#     page.get_by_text("Redirecting in 2 seconds").click()
#     page.get_by_role("img").click()
#     page.get_by_text("One app for Human Resources").click()

#     # ---------------------
#     context.close()
#     browser.close()


# with sync_playwright() as playwright:
#     run(playwright)

# import re
# from playwright.sync_api import Page, expect


# def test_example(page: Page) -> None:
#     page.goto("https://test-pub-hris.robi.com.bd/")
#     page.goto("https://test-pub-hris.robi.com.bd/sign-in?redirectURL=%2Fess%2Fdashboard")
#     page.get_by_label("Email address *").click()
#     page.get_by_label("Email address *").fill("riyad.salehdin@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("Robi@12345$$")
#     page.get_by_role("button", name="Log In").click()
#     page.goto("https://test-pub-hris.robi.com.bd/ess/dashboard")
#     expect(page.get_by_role("link", name="Leave Request")).to_be_visible()
#     page.get_by_role("link", name="Leave Request").click()
#     page.get_by_text("My Leave").click()
#     page.get_by_role("button", name="New Leave Request").click()
#     page.get_by_label("Leave Requestclose").get_by_text("Leave Request").click()
#     page.locator("div").filter(has_text=re.compile(r"^Leave Type \*$")).nth(3).click()
#     page.get_by_role("option", name="Annual Leave").locator("span").click()
#     page.get_by_label("Start Date *").click()
#     page.locator("#automat_start_date").get_by_label("Open calendar").click()
#     page.locator(".cdk-overlay-container > div:nth-child(3)").click()
#     page.get_by_label("Start Date *").click()
#     page.get_by_placeholder("Start Date").click()
#     page.get_by_label("End Date *").click()
#     page.get_by_label("Start Date *").click()
#     page.get_by_placeholder("Start Date").click()
#     page.locator("div").filter(has_text=re.compile(r"^Start Date \*$")).first.click()
#     page.locator("#automat_start_date").get_by_label("Open calendar").click()
#     page.get_by_label("7 January 2025", exact=True).click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("8 January 2025", exact=True).click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("31 January").click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("Next month").click()
#     page.get_by_label("Next month").click()
#     page.get_by_label("21 March").click()
#     page.get_by_label("Start Date *").click()
#     page.locator("#automat_start_date").get_by_label("Open calendar").click()
#     page.get_by_label("7 January 2025", exact=True).click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("10 January").click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("9 January 2025", exact=True).click()
#     page.get_by_placeholder("End Date").click()
#     page.get_by_placeholder("Duration").click()
#     page.locator("#automat_start_date").get_by_label("Open calendar").click()
#     page.get_by_label("7 January 2025", exact=True).click()
#     page.get_by_placeholder("Duration").click()
#     page.get_by_placeholder("Duration").click()
#     page.get_by_placeholder("Duration").click()
#     page.get_by_text("Annual LeaveLeave Type *Start").click()
#     page.get_by_label("Leave Reason *").click()
#     page.get_by_placeholder("Reason (Max limit: 190").fill("Test Leave")
#     page.get_by_placeholder("End Date").click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("8 January 2025", exact=True).click()
#     page.locator("#automat_end_date").get_by_label("Open calendar").click()
#     page.get_by_label("7 January 2025", exact=True).click()
#     page.locator("#automat_start_time").click()
#     page.get_by_role("button", name="Ok").click()
#     page.get_by_placeholder("End Time").click()
#     page.locator("#automat_end_time").click()
#     page.get_by_text("123456789101112").click()
#     page.get_by_text("·················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_text("················································").click()
#     page.get_by_role("button", name="Ok").click()
#     page.get_by_placeholder("Start Time").click()
#     page.locator("#automat_start_time").click()
#     page.get_by_text("123456789101112").click()
#     page.get_by_text("123456789101112").click()
#     page.get_by_text("123456789101112").click()
#     page.get_by_role("button", name="Ok").click()
#     page.get_by_role("button", name="Upload File").click()
#     page.locator("div").filter(has_text=re.compile(r"^Leave Reason \*$")).nth(1).click()
#     page.get_by_role("button", name="Request Now").click()
#     page.get_by_role("button", name="Ok").click()
#     page.get_by_text("Riyad Salehdin").click()
#     page.get_by_role("button", name="Log out").click()
#     page.get_by_role("link", name="sign in").click()
#     page.locator("mat-form-field").filter(has_text="Email address *").click()
#     page.get_by_label("Email address *").fill("rafat.kamal@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("Robi@12345$$")
#     page.get_by_role("button", name="Log In").click()
#     page.get_by_text("View Details").click()
#     page.get_by_text("All Pending Requests").click()
#     page.get_by_text("Pending Leave History").click()
#     page.get_by_text("View Details").click()
#     page.get_by_role("columnheader", name="Employee Name").click()
#     page.locator("span > .ng-tns-c186-72").first.click()
#     page.get_by_text("0.5").first.click()
#     page.get_by_role("row", name="​ Riyad Salehdin 10005540 Annual Leave Jan 07, 2025 - Jan 07, 2025 0.5 View").get_by_role("button").nth(1).click()
#     page.get_by_role("button", name="Confirm").click()
#     page.get_by_role("button", name="Ok").click()
#     page.get_by_text("Mohammad Rafat Kamal").click()
#     page.get_by_role("button", name="Log out").click()
#     page.get_by_text("Go tosign in").click()
#     page.get_by_label("Email address *").click()
#     page.get_by_label("Email address *").fill("riyad.salehdin@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("rafat.kamal@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("bd")
#     page.get_by_label("Password *").press("ArrowRight")
#     page.get_by_label("Password *").press("ArrowRight")
#     page.get_by_label("Password *").fill("Robi@12345$$\"")
#     page.get_by_role("button", name="Log In").click()
#     page.get_by_role("button", name="Log In").click()
#     page.get_by_label("Email address *").click()
#     page.get_by_label("Email address *").fill("riyad.salehdin@robi.com.bd")
#     page.get_by_label("Password *").click()
#     page.get_by_label("Password *").fill("Robi@12345$$")
#     page.get_by_role("button", name="Log In").click()
#     page.get_by_role("link", name="Leave Request").click()
#     page.get_by_role("cell", name="Jan 7,").first.click()
#     page.get_by_role("columnheader", name="Request Date").click()
#     page.locator("td:nth-child(6) > .ng-tns-c186-103").first.click()
#     page.get_by_role("columnheader", name="Request Status").click()
#     page.get_by_role("cell", name="Jan 7,").first.click()
#     page.get_by_role("columnheader", name="Request Date").click()
#     page.get_by_role("columnheader", name="Leave Type").click()
#     page.locator("td:nth-child(2)").first.click()
#     page.get_by_role("columnheader", name="Duration").click()
#     page.get_by_text("Jan 07, 2025 - Jan 07,").click()
#     page.get_by_role("columnheader", name="Count").click()
#     page.get_by_role("columnheader", name="Request Pending At").click()
#     page.locator("td:nth-child(5)").first.click()
